inherit_from:
  - .rubocop_airbnb.yml

Rails:
  Enabled: true

LineLength:
  Max: 310

PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': "[]"

AllCops:
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "node_modules/**/*"
    - "bin/*"
    - "**/Gemfile"
    - "vendor/**/*"
    - ".git/**/*"
    - "spec/**/*"
  NewCops: enable

Layout/BlockAlignment:
  Enabled: false

Airbnb/SimpleModifierConditional:
  Enabled: false