version: 2
jobs:
    build:
        docker:
            - image: alpine
        steps:
            - checkout
            - run:
                name: Echo Test
                command: echo "CircleCI Test"
    deploy:
        machine:
            image: ubuntu-2004:2022.10.1
        steps:
            - checkout
            - add_ssh_keys:
                fingerprints:
                    - fb:53:44:1f:db:4a:93:4c:d3:4e:6f:03:ab:de:cd:5b
            - run: ssh ${USER_NAME}@${HOST_NAME} 'cd /var/www/minagawa-portfolio && git pull'

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build