version: 2.1
jobs:
  build:
    docker:
        - image: cimg/ruby:2.7.6
    steps:
        - checkout
        - run: ruby 2.7.6
  deploy:
    machine:
        image: ubuntu-2004:202201-02
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - db:f5:a7:bd:d9:90:1b:db:e6:8f:8a:f4:35:53:d1:95
      - run: ssh ${USER_NAME}@${HOST_NAME} "/var/www/minagawa-portfolio/deploy.sh"
workflows:
  version: 2
  build_and_deploy:
      jobs:
        - build
        - deploy:
            requires:
                  - build
