version: 2
jobs:
    build:
        docker:
            - image: alpine
        steps:
            - checkout
            - run:
                name: Echo Test
                command: echo "CircleCI Test"
    deploy:
        machine:
            image: circleci/classic:edge
        steps:
            - checkout
            - add_ssh_keys:
                fingerprints:
                  # CircleCI上でSSHキー登録を行った際に作成されるfingerprintsを記入！！
                  - ××:××:××:××:××:××:××:××:××:××:××:××:××:××:××:××
            - run: ssh ${USER_NAME}@${HOST_NAME} 'cd ///var/www/minagawa-portfolio && git pull'

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build