version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
jobs:
  deploy:
    machine:
        image: ubuntu-2004:202201-02
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - ${FINGER_PRINTS}
      - run: ssh ${USER_NAME}@${HOST_NAME} "/var/www/minagawa-portfolio/deploy.sh"
workflows:
  version: 2
  build_and_deploy:
      jobs:
        - build
        - deploy:
            requires:
                  - build
