version: 2.1
jobs:
    build:
        docker:
            - image: alpine
        steps:
            - checkout
            - run:
                name: Echo Test
                command: echo "CircleCI Test"
    deploy:
        machine:
            image: ubuntu-2004:2022.10.1
        steps:
            - checkout
            - add_ssh_keys:
                fingerprints:
                  - 23:4c:51:6d:51:84:a8:89:44:8d:44:1d:f0:e0:d0:0b
            - run: ssh ${USER_NAME}@${HOST_NAME} 'cd ///var/www/minagawa-portfolio && git pull'

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build