version: 2.1
jobs:
    build:
        docker:
            - image: alpine
        steps:
            - checkout
            - run:
                name: Echo Test
                command: echo "CircleCI Test"
    deploy:
        machine:
            image: cimg/ruby:2.7.6-node-browsers
        steps:
            - checkout
            - add_ssh_keys:
                fingerprints:
                  - 77:fc:02:08:71:f9:b1:a1:e8:a5:ea:7d:d0:f3:b3:56
            - run: ssh ${USER_NAME}@${HOST_NAME} 'cd /var/www/minagawa-portfolio && git pull'

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build