version: 2.1
jobs:
    build:
        docker:
            - image: alpine
        steps:
            - checkout
            - run:
                name: Echo Test
                command: echo "CircleCI Test"
    deploy:
        machine:
            image: cimg/ruby:2.7.6-node-browsers
        steps:
            - checkout
            - add_ssh_keys:
                fingerprints:
                    - db:f5:a7:bd:d9:90:1b:db:e6:8f:8a:f4:35:53:d1:95
            - run: ssh ${USER_NAME}@${HOST_NAME} 'cd /var/www/minagawa-portfolio && git pull'

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build